server:
  port: 8080
  forward-headers-strategy: framework

cloud:
  aws:
    region:
      static: ${S3_REGION:ap-northeast-2}
    s3:
      bucket: ${S3_BUCKETNAME:artipcik-s3}

spring:
  profiles:
    active: local
    include:
      - secret
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 30        # 연결 풀 크기 증가
      minimum-idle: 10             # 최소 idle 연결 수
      connection-timeout: 20000    # 연결 타임아웃 20초
      leak-detection-threshold: 60000  # 연결 누수 감지

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 2000ms

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false

jwt:
  secretKey: ${JWT_SECRET_KEY}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION:3600000}
    header: ${JWT_ACCESS_HEADER:Authorization}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION:3600000}
    header: ${JWT_REFRESH_HEADER:RefreshToken}

# Springdoc (Swagger UI)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    display-request-duration: true
    groups-order: ASC

logging:
  level:
    com.likelion.artipick: info

# Weather API 설정
weather:
  api:
    base-url: https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
    auth-key: ${WEATHER_API_KEY}
    current-endpoint: /getUltraSrtNcst    # 실시간
    forecast-endpoint: /getVilageFcst     # 예보

# KaKao API 설정
kakao:
  api:
    key: ${KAKAO_API_KEY}

# AI 서버 설정
ai:
  server:
    url: ${AI_SERVER_URL}

# 문화 예술 정보 API
culture:
  api:
    base-url: https://apis.data.go.kr/B553457/cultureinfo
    auth-key: ${CULTURE_API_KEY}
